name: PlaytimeRewards
version: ${project.version}
main: at.blvckbytes.playtime_rewards.PlaytimeRewardsPlugin
author: BlvckBytes
api-version: 26.1
depend: [Essentials, LuckPerms]
softdepend: [PlaceholderAPI]
commands:
  playtime:
    description: Check your current playtime and AFK time
  rewards:
    description: View your available rewards
  playtop:
    description: View the top leaderboards for playtime
  afktop:
    description: View the top leaderboards for AFK time
  playtimerewards:
    description: The main command, to be used for administrative purposes
    permission: playtimerewards.admin-command